const RoomActionTypes = {
  FETCH_ROOMS_START: "FETCH_ROOMS_START",
  FETCH_ROOMS_SUCCESS: "FETCH_ROOMS_SUCCESS",
  FETCH_ROOMS_FAILURE: "FETCH_ROOMS_FAILURE",
  FETCH_ROOM_DETAILS_START: "FETCH_ROOM_DETAILS_START",
  FETCH_ROOM_DETAILS_SUCCESS: "FETCH_ROOM_DETAILS_SUCCESS",
  FETCH_ROOM_DETAILS_FAILURE: "FETCH_ROOM_DETAILS_FAILURE",
};

export default RoomActionTypes;
